use_frameworks!

platform :ios, '10.0'

target 'CustomAdditionPod_Example' do
  pod 'CustomAdditionPod', :path => '../'

  target 'CustomAdditionPod_Tests' do
    inherit! :search_paths

    
  end
end
